### ISSUE TITLE
Adding the ability to calculate the width and height using the aspect ratio

### ISSUE THREAD

**Issue by AbdKayali3** [ArabianCoconut/aspectratio.github.io#1]
## Enhancement Description:

Currently, the calculator allows users to input the width and height to calculate the aspect ratio. I propose adding functionality to calculate the width and height given a specific aspect ratio and one of the dimensions (width or height).

## Use Case:

This feature would be useful in scenarios where a user has one dimension of an image (either width or height) and wants to maintain a specific aspect ratio. The calculator could provide the missing dimension, ensuring the aspect ratio remains consistent.

## Proposed Implementation:

The user would input:
The aspect ratio (as two integers representing the width and height).
One of the dimensions (either width or height).
The calculator would then output the missing dimension.

## Example:
If a user inputs an aspect ratio of 16:9 and a width of 1920, the calculator will output a height of 1080.

## Potential Challenges:
The main challenge would be handling invalid inputs and ensuring the output is a whole number. If the calculated dimension is not a whole number, the calculator could round to the nearest whole number and notify the user of the adjustment.
</br>

Thank you for considering this enhancement. I believe it would add significant value to the project and its users.

**Comment by ArabianCoconut** [comment]
- approved

- Next update this will be implemented.
